// const webtoonData = [
//   {
//     id: 1,
//     artist_id: 1,
//     title: "First",
//     volume: 1,
//     pages: ["/img_420_420.png", "/img_288_288.png"],
//     description:
//       "Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO.",
//   },
//   {
//     id: 2,
//     artist_id: 1,
//     title: "Second",
//     volume: 1,
//     pages: ["/img_420_420.png", "/img_288_288.png"],
//     description: "Description of TANGO Description of TANGO",
//   },
//   {
//     id: 3,
//     artist_id: 3,
//     title: "Third",
//     volume: 1,
//     pages: ["/img_420_420.png", "/img_288_288.png"],
//     description:
//       "Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO.",
//   },
//   {
//     id: 4,
//     artist_id: 1,
//     title: "Fourth",
//     volume: 1,
//     pages: ["/img_420_420.png", "/img_288_288.png"],
//     description:
//       "Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO.",
//   },
//   {
//     id: 5,
//     artist_id: 2,
//     title: "Daddy's Twenty-Forty-Two",
//     volume: 1,
//     pages: [
//       "/img_420_420.png",
//       "/img_288_288.png",
//       "/logo_black/logo_360.png",
//       "/logo_black/logo_768.png",
//     ],
//     description:
//       "Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO.",
//   },
//   {
//     id: 6,
//     artist_id: 1,
//     title: "Sixth",
//     volume: 1,
//     pages: ["/img_420_420.png", "/img_288_288.png"],
//     description:
//       "Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO.",
//   },
//   {
//     id: 7,
//     artist_id: 1,
//     title: "Tango",
//     volume: 1,
//     pages: ["/img_420_420.png", "/img_288_288.png"],
//     description:
//       "Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO.",
//   },
//   {
//     id: 8,
//     artist_id: 2,
//     title: "Daddy's Twenty-Forty-Five",
//     volume: 1,
//     pages: ["/img_420_420.png", "/img_288_288.png"],
//     description:
//       "Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO.",
//   },
//   {
//     id: 9,
//     artist_id: 2,
//     title: "Daddy's Twenty-Forty-Five",
//     volume: 1,
//     pages: ["/img_420_420.png", "/img_288_288.png"],
//     desc: "Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO.",
//   },
//   {
//     id: 10,
//     artist_id: 1,
//     title: "Tenth",
//     volume: 1,
//     pages: ["/img_420_420.png", "/img_288_288.png"],
//     description:
//       "Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO.",
//   },
//   {
//     id: 11,
//     artist_id: 1,
//     title: "Eleventh",
//     volume: 1,
//     pages: ["/img_420_420.png", "/img_288_288.png"],
//     description:
//       "Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO.",
//   },
//   {
//     id: 12,
//     artist_id: 1,
//     title: "Twelfth",
//     volume: 1,
//     pages: ["/img_420_420.png", "/img_288_288.png"],
//     description: "Description of TANGO Description of TANGO",
//   },
// ];

// const topData = {
//   id: 5,
//   artist_id: 2,
//   title: "Daddy's Twenty-Forty-Two",
//   volume: 1,
//   pages: ["/img_420_420.png", "/img_288_288.png"],
//   description:
//     "Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO. ",
// };

// const NFTData = [
//   {
//     id: 32,
//     webtoon_id: 12,
//     name: "Journey 1",
//     created_by: "ddkang",
//     owned_by: 1,
//     image_address: "/img_288_288.png",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 1,
//     drop_timestamp: "2022-07-26T09:15:00Z",
//     sold: false,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 33,
//     webtoon_id: 12,
//     name: "Journey 2",
//     created_by: "ddkang",
//     owned_by: 1,
//     image_address: "/img_288_288.png",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 1,
//     drop_timestamp: "2021-07-01T16:00:00Z",
//     sold: true,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 34,
//     webtoon_id: 12,
//     name: "Journey 3",
//     created_by: "ddkang",
//     owned_by: 1,
//     image_address: "/img_288_288.png",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 1,
//     drop_timestamp: "2021-07-01T16:00:00Z",
//     sold: true,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 35,
//     webtoon_id: 12,
//     name: "Journey 4",
//     created_by: "ddkang",
//     owned_by: 1,
//     image_address: "/img_288_288.png",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 1,
//     drop_timestamp: "2021-07-01T16:00:00Z",
//     sold: true,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 36,
//     webtoon_id: 12,
//     name: "Journey 5",
//     created_by: "ddkang",
//     owned_by: 2,
//     image_address: "/img_288_288.png",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 1,
//     drop_timestamp: "2021-07-01T16:00:00Z",
//     sold: true,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 29,
//     webtoon_id: 11,
//     name: "Journey 1",
//     created_by: "ddkang",
//     owned_by: 2,
//     image_address: "/img_288_288.png",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 2,
//     drop_timestamp: "2022-07-26T09:15:00Z",
//     sold: false,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 30,
//     webtoon_id: 11,
//     name: "Journey 2",
//     created_by: "ddkang",
//     owned_by: 2,
//     image_address: "/img_288_288.png",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 2,
//     drop_timestamp: "2021-07-01T16:00:00Z",
//     sold: true,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 31,
//     webtoon_id: 11,
//     name: "Journey 3",
//     created_by: "ddkang",
//     owned_by: 2,
//     image_address: "/img_288_288.png",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 2,
//     drop_timestamp: "2021-07-01T16:00:00Z",
//     sold: true,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 26,
//     webtoon_id: 10,
//     name: "Journey 1",
//     created_by: "ddkang",
//     owned_by: 3,
//     image_address: "/img_288_288.png",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 3,
//     drop_timestamp: "2021-07-01T16:00:00Z",
//     sold: true,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 27,
//     webtoon_id: 10,
//     name: "Journey 2",
//     created_by: "ddkang",
//     owned_by: 3,
//     image_address: "/img_288_288.png",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 3,
//     drop_timestamp: "2021-07-01T16:00:00Z",
//     sold: true,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 28,
//     webtoon_id: 10,
//     name: "Journey 3",
//     created_by: "ddkang",
//     owned_by: 3,
//     image_address: "/img_288_288.png",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 3,
//     drop_timestamp: "2021-07-01T16:00:00Z",
//     sold: true,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 23,
//     webtoon_id: 9,
//     name: "Journey 1",
//     created_by: "Puroon",
//     owned_by: 3,
//     image_address: "/img_288_288.png",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 1,
//     drop_timestamp: "2022-07-01T16:00:00Z",
//     sold: false,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 24,
//     webtoon_id: 9,
//     name: "Journey 2",
//     created_by: "Puroon",
//     owned_by: 3,
//     image_address: "/img_288_288.png",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 1,
//     drop_timestamp: "2021-07-01T16:00:00Z",
//     sold: true,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 25,
//     webtoon_id: 9,
//     name: "Daddy's Twenty-Forty-Five",
//     created_by: "Puroon",
//     owned_by: 4,
//     image_address: "/img_288_288.png",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 1,
//     drop_timestamp: "2021-07-01T16:00:00Z",
//     sold: true,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 20,
//     webtoon_id: 8,
//     name: "Journey 1",
//     created_by: "Puroon",
//     owned_by: 4,
//     image_address: "/img_288_288.png",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 2,
//     drop_timestamp: "2022-07-01T16:00:00Z",
//     sold: false,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 21,
//     webtoon_id: 8,
//     name: "Journey 2",
//     created_by: "Puroon",
//     owned_by: 4,
//     image_address: "/img_288_288.png",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 2,
//     drop_timestamp: "2021-07-01T16:00:00Z",
//     sold: true,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 22,
//     webtoon_id: 8,
//     name: "Journey 3",
//     created_by: "Puroon",
//     owned_by: 4,
//     image_address: "/img_288_288.png",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 2,
//     drop_timestamp: "2021-07-01T16:00:00Z",
//     sold: true,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 17,
//     webtoon_id: 7,
//     name: "Journey 1",
//     created_by: "ddkang",
//     owned_by: 4,
//     image_address: "/img_288_288.png",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 4,
//     drop_timestamp: "2022-07-01T16:00:00Z",
//     sold: false,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 18,
//     webtoon_id: 7,
//     name: "Journey 2",
//     image_address: "/img_288_288.png",
//     created_by: "ddkang",
//     owned_by: 4,
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 4,
//     drop_timestamp: "2021-07-01T16:00:00Z",
//     sold: true,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 14,
//     webtoon_id: 6,
//     name: "Journey 1",
//     created_by: "ddkang",
//     owned_by: 5,
//     image_address: "/img_288_288.png",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 5,
//     drop_timestamp: "2022-07-01T16:00:00Z",
//     sold: false,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 15,
//     webtoon_id: 6,
//     name: "Journey 2",
//     created_by: "ddkang",
//     owned_by: 5,
//     image_address: "/img_288_288.png",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 5,
//     drop_timestamp: "2021-07-01T16:00:00Z",
//     sold: true,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 11,
//     webtoon_id: 5,
//     name: "Journey 1",
//     created_by: "Puroon",
//     owned_by: 5,
//     image_address: "/img_288_288.png",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 3,
//     drop_timestamp: "2022-07-26T09:15:00Z",
//     sold: false,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 12,
//     webtoon_id: 5,
//     name: "Journey 2",
//     created_by: "Puroon",
//     owned_by: 5,
//     image_address: "/img_288_288.png",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 3,
//     drop_timestamp: "2021-07-01T16:00:00Z",
//     sold: true,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 6,
//     webtoon_id: 3,
//     name: "Journey 1",
//     created_by: "chunduck",
//     owned_by: 5,
//     image_address: "/img_288_288.png",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 1,
//     drop_timestamp: "2021-07-01T16:00:00Z",
//     sold: true,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 7,
//     webtoon_id: 3,
//     name: "Journey 2",
//     created_by: "chunduck",
//     owned_by: 2,
//     image_address: "/img_288_288.png",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 1,
//     drop_timestamp: "2021-07-01T16:00:00Z",
//     sold: true,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 8,
//     webtoon_id: 3,
//     name: "Journey 3",
//     created_by: "chunduck",
//     owned_by: 2,
//     image_address: "/img_288_288.png",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 1,
//     drop_timestamp: "2021-07-01T16:00:00Z",
//     sold: true,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 3,
//     webtoon_id: 2,
//     name: "Journey 11",
//     created_by: "ddkang",
//     owned_by: 2,
//     image_address: "/img_288_288.png",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 1,
//     drop_timestamp: "2021-07-01T16:00:00Z",
//     sold: true,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 4,
//     webtoon_id: 2,
//     name: "Journey 12",
//     created_by: "ddkang",
//     owned_by: 2,
//     image_address: "/img_288_288.png",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 1,
//     drop_timestamp: "2021-07-01T16:00:00Z",
//     sold: true,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 5,
//     webtoon_id: 2,
//     name: "Journey 13",
//     created_by: "ddkang",
//     owned_by: 2,
//     image_address: "/img_288_288.png",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 1,
//     drop_timestamp: "2021-07-01T16:00:00Z",
//     sold: true,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 1,
//     webtoon_id: 1,
//     created_by: "ddkang",
//     owned_by: 2,
//     name: "Journey 12",
//     image_address: "/img_288_288.png",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 2,
//     drop_timestamp: "2021-07-01T16:00:00Z",
//     sold: true,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 2,
//     webtoon_id: 1,
//     name: "Journey 11",
//     owned_by: 1,
//     image_address: "/img_288_288.png",
//     created_by: "ddkang",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 2,
//     drop_timestamp: "2021-07-01T16:00:00Z",
//     sold: true,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 37,
//     webtoon_id: 1,
//     name: "Journey 11",
//     owned_by: 3,
//     image_address: "/img_288_288.png",
//     created_by: "ddkang",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 3,
//     drop_timestamp: "2021-07-01T16:00:00Z",
//     sold: true,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 38,
//     webtoon_id: 1,
//     name: "Journey 11",
//     owned_by: 4,
//     image_address: "/img_288_288.png",
//     created_by: "ddkang",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 4,
//     drop_timestamp: "2021-07-01T16:00:00Z",
//     sold: true,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 39,
//     webtoon_id: 1,
//     name: "Journey 11",
//     owned_by: 5,
//     image_address: "/img_288_288.png",
//     created_by: "ddkang",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 5,
//     drop_timestamp: "2021-07-01T16:00:00Z",
//     sold: true,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 40,
//     webtoon_id: 1,
//     name: "Journey 11",
//     owned_by: 6,
//     image_address: "/img_288_288.png",
//     created_by: "ddkang",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 6,
//     drop_timestamp: "2021-07-01T16:00:00Z",
//     sold: true,
//     opensea: "https://opensea.io/",
//   },
//   {
//     id: 41,
//     webtoon_id: 1,
//     name: "Journey 11",
//     owned_by: 1,
//     image_address: "/img_288_288.png",
//     created_by: "ddkang",
//     description:
//       "Description Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT Description of NFT.",
//     price: 0.0263,
//     edition: 7,
//     drop_timestamp: "2021-07-01T16:00:00Z",
//     sold: true,
//     opensea: "https://opensea.io/",
//   },
// ];

// const artistData = [
//   {
//     id: 1,
//     name: "ddkang",
//     description:
//       "ddkangddkangddkang ddkangddkangddkangddkang. ddkangddkang ddkangddkang ddkangddkangddkang",
//     profile_picture: "/img_420_420.png",
//     background_picture: "/Frame_4592_1.png",
//     email: "d_d_kang@gmail.com",
//     instagram: "d_d_kang",
//     twitter: "d_d_kang",
//     wallet_address: "0xd05...cDb80",
//     opensea: "https://opensea.io/",
//     collection: [],
//   },
//   {
//     id: 2,
//     name: "Puroon",
//     description:
//       "ddkangddkangddkang ddkangddkangddkangddkang. ddkangddkang ddkangddkang ddkangddkangddkang",
//     profile_picture: "/img_420_420.png",
//     background_picture: "/Frame_4592_1.png",
//     email: "d_d_kang@gmail.com",
//     instagram: "d_d_kang",
//     twitter: "d_d_kang",
//     wallet_address: "0xd05...cDb80",
//     opensea: "https://opensea.io/",
//     collection: [],
//   },
//   {
//     id: 3,
//     name: "chunduck",
//     description:
//       "ddkangddkangddkang ddkangddkangddkangddkang. ddkangddkang ddkangddkang ddkangddkangddkang",
//     profile_picture: "/img_420_420.png",
//     background_picture: "/Frame_4592_1.png",
//     email: "d_d_kang@gmail.com",
//     instagram: "d_d_kang",
//     twitter: "d_d_kang",
//     wallet_address: "0xd05...cDb80",
//     opensea: "https://opensea.io/",
//     collection: [],
//   },
//   {
//     id: 4,
//     name: "abc",
//     description:
//       "ddkangddkangddkang ddkangddkangddkangddkang. ddkangddkang ddkangddkang ddkangddkangddkang",
//     profile_picture: "/img_420_420.png",
//     background_picture: "/Frame_4592_1.png",
//     email: "d_d_kang@gmail.com",
//     instagram: "d_d_kang",
//     twitter: "d_d_kang",
//     wallet_address: "0xd05...cDb80",
//     opensea: "https://opensea.io/",
//     collection: [],
//   },
// ];

// const userData = [
//   {
//     profile_picture: "",
//     wallet_address: "0xd05...cDb80",
//     name: "rarement",
//     id: 1,
//   },
//   {
//     profile_picture: "",
//     wallet_address: "0xd05...cDb80",
//     name: "rarement",
//     id: 2,
//   },
//   {
//     profile_picture: "/img_420_420.png",
//     wallet_address: "0xd05...cDb80",
//     name: "rarement",
//     id: 3,
//   },
//   {
//     profile_picture: "/img_420_420.png",
//     wallet_address: "0xd05...cDb80",
//     name: "rarement",
//     id: 4,
//   },
//   {
//     profile_picture: "/img_420_420.png",
//     wallet_address: "0xd05...cDb80",
//     name: "rarement",
//     id: 5,
//   },
//   {
//     profile_picture: "/img_420_420.png",
//     wallet_address: "0xd05...cDb80",
//     name: "rarement",
//     id: 6,
//   },
//   {
//     profile_picture: "/img_420_420.png",
//     wallet_address: "0xd05...cDb80",
//     name: "rarement",
//     id: 7,
//   },
// ];

// export { topData, webtoonData, NFTData, artistData, userData };
