//to be changed later
const webtoonData = [
  {
    id: 1,
    profile: "/img_420_420.png",
    author: "author",
    profileLink: "/",
    title: "First",
    vol: 1,
    cover: "/img_420_420.png",
    pages: ["/img_420_420.png", "/img_288_288.png"],
    desc: "Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO.",
    authorDesc:
      "ddkangddkangddkangddkangddkangddkangddkang.ddkangddkangddkangddkangddkangddkangddkang",
    authorEmail: "d_d_kang@gmail.com",
    authorInstagram: "@d_d_kang",
    authorWallet: "0xd05...cDb80",
    authorWalletLink: "/",
    collectors: [
      { id: 1, profile: "/img_420_420.png" },
      { id: 2, profile: "/img_420_420.png" },
    ],
    nft: [
      {
        id: 1,
        name: "Journey 2",
        price: 0.0263,
        edition: 2,
        targetTime: "2021-07-01T16:00:00Z",
        minted: true,
        sold: true,
      },
      {
        id: 2,
        name: "Journey 1",
        price: 0.0263,
        edition: 1,
        targetTime: "2021-07-01T16:00:00Z",
        minted: true,
        sold: true,
      },
    ],
  },
  {
    id: 2,
    profile: "/img_420_420.png",
    author: "author",
    profileLink: "/",
    title: "Second",
    vol: 1,
    cover: "/img_420_420.png",
    pages: ["/img_420_420.png", "/img_288_288.png"],
    desc: "Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO.",
    authorDesc:
      "ddkangddkangddkangddkangddkangddkangddkang.ddkangddkangddkangddkangddkangddkangddkang",
    authorEmail: "d_d_kang@gmail.com",
    authorInstagram: "@d_d_kang",
    authorWallet: "0xd05...cDb80",
    authorWalletLink: "/",
    collectors: [
      { id: 1, profile: "/img_420_420.png" },
      { id: 2, profile: "/img_420_420.png" },
    ],
    nft: [
      {
        id: 1,
        name: "Journey 1",
        price: 0.0263,
        edition: 1,
        targetTime: "2021-07-01T16:00:00Z",
        minted: true,
        sold: true,
      },
      {
        id: 2,
        name: "Journey 2",
        price: 0.0263,
        edition: 2,
        targetTime: "2021-07-01T16:00:00Z",
        minted: true,
        sold: true,
      },
      {
        id: 3,
        name: "Journey 3",
        price: 0.0263,
        edition: 3,
        targetTime: "2021-07-01T16:00:00Z",
        minted: true,
        sold: true,
      },
    ],
  },
  {
    id: 3,
    profile: "/img_420_420.png",
    author: "author",
    profileLink: "/",
    title: "Third",
    vol: 1,
    cover: "/img_420_420.png",
    pages: ["/img_420_420.png", "/img_288_288.png"],
    desc: "Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO.",
    authorDesc:
      "ddkangddkangddkangddkangddkangddkangddkang.ddkangddkangddkangddkangddkangddkangddkang",
    authorEmail: "d_d_kang@gmail.com",
    authorInstagram: "@d_d_kang",
    authorWallet: "0xd05...cDb80",
    authorWalletLink: "/",
    collectors: [
      { id: 1, profile: "/img_420_420.png" },
      { id: 2, profile: "/img_420_420.png" },
    ],
    nft: [
      {
        id: 1,
        name: "Journey 1",
        price: 0.0263,
        edition: 1,
        targetTime: "2021-07-01T16:00:00Z",
        minted: true,
        sold: false,
      },
      {
        id: 2,
        name: "Journey 2",
        price: 0.0263,
        edition: 2,
        targetTime: "2021-07-01T16:00:00Z",
        minted: true,
        sold: true,
      },
      {
        id: 3,
        name: "Journey 3",
        price: 0.0263,
        edition: 3,
        targetTime: "2021-07-01T16:00:00Z",
        minted: true,
        sold: false,
      },
    ],
  },
  {
    id: 4,
    profile: "/img_420_420.png",
    author: "author",
    profileLink: "/",
    title: "Fourth",
    vol: 1,
    cover: "/img_420_420.png",
    pages: ["/img_420_420.png", "/img_288_288.png"],
    desc: "Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO.",
    authorDesc:
      "ddkangddkangddkangddkangddkangddkangddkang.ddkangddkangddkangddkangddkangddkangddkang",
    authorEmail: "d_d_kang@gmail.com",
    authorInstagram: "@d_d_kang",
    authorWallet: "0xd05...cDb80",
    authorWalletLink: "/",
    collectors: [
      { id: 1, profile: "/img_420_420.png" },
      { id: 2, profile: "/img_420_420.png" },
    ],
    nft: [
      {
        id: 1,
        name: "Journey 2",
        price: 0.0263,
        edition: 2,
        targetTime: "2021-07-01T16:00:00Z",
        minted: true,
        sold: true,
      },
      {
        id: 2,
        name: "Journey 3",
        price: 0.0263,
        edition: 3,
        targetTime: "2021-07-01T16:00:00Z",
        minted: true,
        sold: false,
      },
    ],
  },
  {
    id: 5,
    profile: "/img_420_420.png",
    author: "author",
    profileLink: "/",
    title: "daddy's twenty-forty-two",
    vol: 1,
    cover: "/img_420_420.png",
    pages: ["/img_420_420.png", "/img_288_288.png"],
    desc: "Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO.",
    authorDesc:
      "ddkangddkangddkangddkangddkangddkangddkang.ddkangddkangddkangddkangddkangddkangddkang",
    authorEmail: "d_d_kang@gmail.com",
    authorInstagram: "@d_d_kang",
    authorWallet: "0xd05...cDb80",
    authorWalletLink: "/",
    collectors: [
      { id: 1, profile: "/img_420_420.png" },
      { id: 2, profile: "/img_420_420.png" },
    ],
    nft: [
      {
        id: 1,
        name: "Journey 1",
        price: 0.0263,
        edition: 1,
        targetTime: "2022-07-01T16:00:00Z",
        minted: false,
        sold: false,
      },
      {
        id: 2,
        name: "Journey 2",
        price: 0.0263,
        edition: 2,
        targetTime: "2021-07-01T16:00:00Z",
        minted: true,
        sold: true,
      },
      {
        id: 3,
        name: "Journey 3",
        price: 0.0263,
        edition: 3,
        targetTime: "2021-07-01T16:00:00Z",
        minted: true,
        sold: false,
      },
    ],
  },
  {
    id: 6,
    profile: "/img_420_420.png",
    author: "author",
    profileLink: "/",
    title: "Sixth",
    vol: 1,
    cover: "/img_420_420.png",
    pages: ["/img_420_420.png", "/img_288_288.png"],
    desc: "Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO.",
    authorDesc:
      "ddkangddkangddkangddkangddkangddkangddkang.ddkangddkangddkangddkangddkangddkangddkang",
    authorEmail: "d_d_kang@gmail.com",
    authorInstagram: "@d_d_kang",
    authorWallet: "0xd05...cDb80",
    authorWalletLink: "/",
    collectors: [
      { id: 1, profile: "/img_420_420.png" },
      { id: 2, profile: "/img_420_420.png" },
    ],
    nft: [
      {
        id: 1,
        name: "Journey 1",
        price: 0.0263,
        edition: 1,
        targetTime: "2022-07-01T16:00:00Z",
        minted: false,
        sold: false,
      },
      {
        id: 2,
        name: "Journey 2",
        price: 0.0263,
        edition: 2,
        targetTime: "2021-07-01T16:00:00Z",
        minted: true,
        sold: true,
      },
      {
        id: 3,
        name: "Journey 3",
        price: 0.0263,
        edition: 3,
        targetTime: "2021-07-01T16:00:00Z",
        minted: true,
        sold: false,
      },
    ],
  },
  {
    id: 7,
    profile: "/img_420_420.png",
    author: "author",
    profileLink: "/",
    title: "Tango",
    vol: 1,
    cover: "/img_420_420.png",
    pages: ["/img_420_420.png", "/img_288_288.png"],
    desc: "Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO.",
    authorDesc:
      "ddkangddkangddkangddkangddkangddkangddkang.ddkangddkangddkangddkangddkangddkangddkang",
    authorEmail: "d_d_kang@gmail.com",
    authorInstagram: "@d_d_kang",
    authorWallet: "0xd05...cDb80",
    authorWalletLink: "/",
    collectors: [
      { id: 1, profile: "/img_420_420.png" },
      { id: 2, profile: "/img_420_420.png" },
    ],
    nft: [
      {
        id: 1,
        name: "Journey 1",
        price: 0.0263,
        edition: 1,
        targetTime: "2022-07-01T16:00:00Z",
        minted: false,
        sold: false,
      },
      {
        id: 2,
        name: "Journey 2",
        price: 0.0263,
        edition: 2,
        targetTime: "2021-07-01T16:00:00Z",
        minted: true,
        sold: true,
      },
      {
        id: 3,
        name: "Journey 3",
        price: 0.0263,
        edition: 3,
        targetTime: "2021-07-01T16:00:00Z",
        minted: true,
        sold: false,
      },
    ],
  },
  {
    id: 8,
    profile: "/img_420_420.png",
    author: "author",
    profileLink: "/",
    title: "Daddy's Twenty-Forty-Five",
    vol: 1,
    cover: "/img_420_420.png",
    pages: ["/img_420_420.png", "/img_288_288.png"],
    desc: "Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO.",
    authorDesc:
      "ddkangddkangddkangddkangddkangddkangddkang.ddkangddkangddkangddkangddkangddkangddkang",
    authorEmail: "d_d_kang@gmail.com",
    authorInstagram: "@d_d_kang",
    authorWallet: "0xd05...cDb80",
    authorWalletLink: "/",
    collectors: [
      { id: 1, profile: "/img_420_420.png" },
      { id: 2, profile: "/img_420_420.png" },
    ],
    nft: [
      {
        id: 1,
        name: "Journey 1",
        price: 0.0263,
        edition: 1,
        targetTime: "2022-07-01T16:00:00Z",
        minted: false,
        sold: false,
      },
      {
        id: 2,
        name: "Journey 2",
        price: 0.0263,
        edition: 2,
        targetTime: "2021-07-01T16:00:00Z",
        minted: true,
        sold: true,
      },
      {
        id: 3,
        name: "Journey 3",
        price: 0.0263,
        edition: 3,
        targetTime: "2021-07-01T16:00:00Z",
        minted: true,
        sold: false,
      },
    ],
  },
  {
    id: 9,
    profile: "/img_420_420.png",
    author: "author",
    profileLink: "/",
    title: "Daddy's Twenty-Forty-Five",
    vol: 1,
    cover: "/img_420_420.png",
    pages: ["/img_420_420.png", "/img_288_288.png"],
    desc: "Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO.",
    authorDesc:
      "ddkangddkangddkangddkangddkangddkangddkang.ddkangddkangddkangddkangddkangddkangddkang",
    authorEmail: "d_d_kang@gmail.com",
    authorInstagram: "@d_d_kang",
    authorWallet: "0xd05...cDb80",
    authorWalletLink: "/",
    collectors: [
      { id: 1, profile: "/img_420_420.png" },
      { id: 2, profile: "/img_420_420.png" },
    ],
    nft: [
      {
        id: 1,
        name: "Journey 1",
        price: 0.0263,
        edition: 1,
        targetTime: "2022-07-01T16:00:00Z",
        minted: false,
        sold: false,
      },
      {
        id: 2,
        name: "Journey 2",
        price: 0.0263,
        edition: 2,
        targetTime: "2021-07-01T16:00:00Z",
        minted: true,
        sold: true,
      },
      {
        id: 3,
        name: "Journey 3",
        price: 0.0263,
        edition: 3,
        targetTime: "2021-07-01T16:00:00Z",
        minted: true,
        sold: false,
      },
    ],
  },
  {
    id: 10,
    profile: "/img_420_420.png",
    author: "author",
    profileLink: "/",
    title: "Daddy's Twenty-Forty-Five",
    vol: 1,
    cover: "/img_420_420.png",
    pages: ["/img_420_420.png", "/img_288_288.png"],
    desc: "Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO.",
    authorDesc:
      "ddkangddkangddkangddkangddkangddkangddkang.ddkangddkangddkangddkangddkangddkangddkang",
    authorEmail: "d_d_kang@gmail.com",
    authorInstagram: "@d_d_kang",
    authorWallet: "0xd05...cDb80",
    authorWalletLink: "/",
    collectors: [
      { id: 1, profile: "/img_420_420.png" },
      { id: 2, profile: "/img_420_420.png" },
    ],
    nft: [
      {
        id: 1,
        name: "Journey 1",
        price: 0.0263,
        edition: 1,
        targetTime: "2022-07-01T16:00:00Z",
        minted: false,
        sold: false,
      },
      {
        id: 2,
        name: "Journey 2",
        price: 0.0263,
        edition: 2,
        targetTime: "2021-07-01T16:00:00Z",
        minted: true,
        sold: true,
      },
      {
        id: 3,
        name: "Journey 3",
        price: 0.0263,
        edition: 3,
        targetTime: "2021-07-01T16:00:00Z",
        minted: true,
        sold: false,
      },
    ],
  },
  {
    id: 11,
    profile: "/img_420_420.png",
    author: "author",
    profileLink: "/",
    title: "Eleventh",
    vol: 1,
    cover: "/img_420_420.png",
    pages: ["/img_420_420.png", "/img_288_288.png"],
    desc: "Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO.",
    authorDesc:
      "ddkangddkangddkangddkangddkangddkangddkang.ddkangddkangddkangddkangddkangddkangddkang",
    authorEmail: "d_d_kang@gmail.com",
    authorInstagram: "@d_d_kang",
    authorWallet: "0xd05...cDb80",
    authorWalletLink: "/",
    collectors: [
      { id: 1, profile: "/img_420_420.png" },
      { id: 2, profile: "/img_420_420.png" },
    ],
    nft: [
      {
        id: 1,
        name: "Journey 1",
        price: 0.0263,
        edition: 1,
        targetTime: "2022-07-01T16:00:00Z",
        minted: false,
        sold: false,
      },
      {
        id: 2,
        name: "Journey 2",
        price: 0.0263,
        edition: 2,
        targetTime: "2021-07-01T16:00:00Z",
        minted: true,
        sold: true,
      },
      {
        id: 3,
        name: "Journey 3",
        price: 0.0263,
        edition: 3,
        targetTime: "2021-07-01T16:00:00Z",
        minted: true,
        sold: false,
      },
    ],
  },
  {
    id: 12,
    profile: "/img_420_420.png",
    author: "author",
    profileLink: "/",
    title: "Twelfth",
    vol: 1,
    cover: "/img_420_420.png",
    pages: ["/img_420_420.png", "/img_288_288.png"],
    desc: "Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO.",
    authorDesc:
      "ddkangddkangddkangddkangddkangddkangddkang.ddkangddkangddkangddkangddkangddkangddkang",
    authorEmail: "d_d_kang@gmail.com",
    authorInstagram: "@d_d_kang",
    authorWallet: "0xd05...cDb80",
    authorWalletLink: "/",
    collectors: [
      { id: 1, profile: "/img_420_420.png" },
      { id: 2, profile: "/img_420_420.png" },
    ],
    nft: [
      {
        id: 1,
        name: "Journey 1",
        price: 0.0263,
        edition: 1,
        targetTime: "2022-07-01T16:00:00Z",
        minted: false,
        sold: false,
      },
      {
        id: 2,
        name: "Journey 2",
        price: 0.0263,
        edition: 2,
        targetTime: "2021-07-01T16:00:00Z",
        minted: true,
        sold: true,
      },
      {
        id: 3,
        name: "Journey 3",
        price: 0.0263,
        edition: 3,
        targetTime: "2021-07-01T16:00:00Z",
        minted: true,
        sold: false,
      },
    ],
  },
];

const topData = {
  id: 5,
  profile: "/img_420_420.png",
  author: "author",
  profileLink: "/",
  title: "daddy's twenty-forty-two",
  vol: 1,
  cover: "/img_420_420.png",
  pages: ["/img_420_420.png", "/img_288_288.png"],
  desc: "Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO Description of TANGO. Description of TANGO Description of TANGO Description of TANGO Description Description of TANGO Description of TANGO.",
  authorDesc:
    "ddkangddkangddkangddkangddkangddkangddkang.ddkangddkangddkangddkangddkangddkangddkang",
  authorEmail: "d_d_kang@gmail.com",
  authorInstagram: "@d_d_kang",
  authorWallet: "12345",
  authorWalletLink: "/",
  collectors: [
    { id: 1, profile: "/img_420_420.png" },
    { id: 2, profile: "/img_420_420.png" },
  ],
  nft: [
    {
      id: 1,
      name: "Journey 1",
      price: 0.0263,
      edition: 1,
      targetTime: "2022-07-01T16:00:00Z",
      minted: false,
      sold: false,
    },
    {
      id: 2,
      name: "Journey 2",
      price: 0.0263,
      edition: 2,
      targetTime: "2021-07-01T16:00:00Z",
      minted: true,
      sold: true,
    },
    {
      id: 3,
      name: "Journey 3",
      price: 0.0263,
      edition: 3,
      targetTime: "2021-07-01T16:00:00Z",
      minted: true,
      sold: false,
    },
  ],
};

// show latest & unminted first and remove topCard item
const listData = webtoonData
  .sort((a, b) => b.id - a.id)
  .sort((a, b) => a.minted - b.minted)
  .filter((item) => item.id !== topData.id);

export { topData, listData, webtoonData };
