import Head from 'next/head'
import Image from 'next/image'
import About from '../comps/About'
import TopCard from '../comps/TopCard'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <TopCard />
        <About />
      </main>
      
    </div>
  )
}
