import Head from 'next/head'
import About from '../homeComps/About'
import { listData, topData } from '../homeComps/Homedata'
import List from '../homeComps/List/List'
import TopCard from '../homeComps/TopCard/TopCard'

export default function Home() {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TopCard data={topData}/>
        <List data={listData} />
        <About />
      </main>
    </div>
  )
}
